version: '3.9'

networks:
  messagingservicenet:
    external: true

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - messagingservicenet
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    networks:
      - messagingservicenet
  redis:
    container_name: redis
    image: 'redis/redis-stack:7.2.0-v0'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=root
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - messagingservicenet
volumes:
  redis-data:
    name: redis-data
